# Generated by Django 5.1.6 on 2025-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_femaletoilet_multifunctionaltoilet_stationticketgate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletmaster',
            name='toilet_root',
            field=models.TextField(null=True),
        ),
    ]
